name: 'Check Android ELF Alignment'
description: 'Check ELF alignment of native libraries in .apk and .so files for Android apps'
author: 'dermochelys'
branding:
  icon: 'check-circle'
  color: 'green'

inputs:
  path:
    description: 'Path to search for .apk and .so files (default: current directory)'
    required: false
    default: './'
  fail-on-unaligned:
    description: 'Fail the action if unaligned 64-bit libraries are found, or if only 32-bit libraries are present'
    required: false
    default: 'true'

outputs:
  apk-results:
    description: 'Results of .apk file alignment checks'
  so-results:
    description: 'Results of .so file alignment checks'

runs:
  using: 'composite'
  steps:
    - name: Check .apk files
      shell: bash
      run: |
        find "${{ inputs.path }}" -iname '*.apk' -type f | xargs -L1 ${{ github.action_path }}/build-scripts/check_elf_alignment.sh
    - name: Check .so files
      shell: bash
      run: |
        find "${{ inputs.path }}" -iname '*.so' -type f | xargs -L1 ${{ github.action_path }}/build-scripts/check_elf_alignment.sh

